graph TD
    api[api]
    builder[builder]
    cache[cache]
    calendar[calendar]
    captcha[captcha]
    chart[chart]
    color[color]
    component[component]
    cropper[cropper]
    crypto[crypto]
    datepicker[datepicker]
    device[device]
    editor[editor]
    engine[engine]
    flowchart[flowchart]
    form[form]
    git[git]
    http[http]
    i18n[i18n]
    icons[icons]
    kit[kit]
    launcher[launcher]
    map[map]
    pdf[pdf]
    progress[progress]
    qrcode[qrcode]
    router[router]
    shared[shared]
    size[size]
    store[store]
    table[table]
    template[template]
    theme[theme]
    tree[tree]
    video[video]
    watermark[watermark]
    websocket[websocket]

    api --> http
    api -.->|dev| builder
    builder --> kit
    cache -.->|dev| builder
    calendar --> shared
    calendar -.->|dev| builder
    captcha -.->|dev| builder
    chart --> shared
    chart -.->|dev| builder
    color --> shared
    color -.->|dev| builder
    component -.->|dev| builder
    component -.->|dev| launcher
    cropper --> shared
    cropper -.->|dev| builder
    crypto -.->|dev| builder
    datepicker -.->|dev| builder
    datepicker -.->|dev| launcher
    device -.->|dev| builder
    editor -.->|dev| builder
    editor -.->|dev| launcher
    editor -.->|dev| shared
    engine -.->|dev| builder
    flowchart --> shared
    flowchart -.->|dev| builder
    flowchart -.->|dev| launcher
    form -.->|dev| builder
    form -.->|dev| launcher
    form -.->|dev| shared
    git --> kit
    git -.->|dev| builder
    http -.->|dev| builder
    i18n -.->|dev| builder
    map -.->|dev| builder
    map -.->|dev| launcher
    pdf -.->|dev| builder
    progress -.->|dev| builder
    progress -.->|dev| launcher
    qrcode -.->|dev| builder
    router --> device
    router -.->|dev| builder
    router -.->|dev| engine
    router -.->|dev| template
    shared -.->|dev| builder
    size -.->|dev| builder
    store -.->|dev| builder
    table --> shared
    table -.->|dev| builder
    template --> cache
    template --> device
    template --> engine
    template --> shared
    template -.->|dev| builder
    theme --> color
    theme -.->|dev| builder
    tree --> shared
    tree -.->|dev| builder
    video -.->|dev| builder
    video -.->|dev| launcher
    watermark -.->|dev| builder
    websocket --> shared
    websocket -.->|dev| builder
