packages:
  # Core packages
  - 'packages/*'
  - 'packages/*/packages/*'
  
  # Libraries
  - 'libraries/*'
  - 'libraries/*/packages/*'
  - '**/examples/*'
  - '**/example'
  # Tools
  - 'tools/*'
  
  # Applications
  - 'apps/*'
  
  # Exclude test projects and non-package directories
  - '!**/test-project'
  - '!**/tests/fixtures'
  - '!tools/cli/src/*'
  - '!**/node_modules'
  - '!**/dist'
  - '!**/es'
  - '!**/lib'