export { CacheConfig, CacheItem, CacheStrategy, DeepReadonly, DeviceAdapterConfig, DeviceType, EventData, EventListener, EventType, ExternalTemplate, ExtractFunction, ExtractPromise, LoadResult, LoaderConfig, Optional, PluginConfig, PluginInstallOptions, PreloadStrategy, Required, ScanResult, ScannerConfig, TemplateConfig, TemplateExtensionOptions, TemplateFileInfo, TemplateIndex, TemplateInfo, TemplateManagerConfig, TemplateMetadata, TemplateRegistryItem, TemplateRendererProps, TemplateStatus, VueApp, VueComponent } from './types/index.js';
export { DeviceAdapter } from './core/device-adapter.js';
export { TemplateLoader } from './core/loader.js';
export { TemplateManager, TemplateManager as default } from './core/manager.js';
export { TemplateScanner } from './core/scanner.js';
export { CacheService } from './services/cache-service.js';
export { DeviceService } from './services/device-service.js';
export { cacheUtils, deviceUtils, errorUtils, logUtils, performanceUtils, templateUtils } from './utils/index.js';
export { useTemplate, useTemplateCache, useTemplateScanner } from './vue/composables/useTemplate.js';
export { createExternalTemplate, createExternalTemplateFromPath, useTemplateExtension } from './vue/composables/useTemplateExtension.js';
export { useTemplateRegistry } from './vue/composables/useTemplateRegistry.js';
export { installTemplateDirectives, templateDirectives, vTemplate, vTemplateCache, vTemplateLazy, vTemplatePreload } from './vue/directives/template.js';
export { TemplateManagerSymbol, default as TemplatePlugin, configureTemplateManager, createTemplatePlugin, install, useTemplateManager } from './vue/plugin.js';
export { TemplateEnginePluginOptions, createDefaultTemplateEnginePlugin, createTemplateEnginePlugin } from './engine/plugin.js';
