// Auto-generated Vue 3 icon components
// Do not edit this file directly

export { default as HeartIcon } from './HeartIcon.ts';
export { default as HomeIcon } from './HomeIcon.ts';
export { default as SearchIcon } from './SearchIcon.ts';
export { default as SettingsIcon } from './SettingsIcon.ts';
export { default as UserIcon } from './UserIcon.ts';

export type { HeartIconProps } from './HeartIcon.ts';
export type { HomeIconProps } from './HomeIcon.ts';
export type { SearchIconProps } from './SearchIcon.ts';
export type { SettingsIconProps } from './SettingsIcon.ts';
export type { UserIconProps } from './UserIcon.ts';


// Common types
export interface IconProps {
  size?: string | number;
  color?: string;
  spin?: boolean;
  pulse?: boolean;
  theme?: 'primary' | 'secondary' | 'success' | 'warning' | 'error' | 'info';
  strokeWidth?: string | number;
  class?: string | string[] | Record<string, boolean>;
  style?: string | Record<string, any>;
}

export type IconComponent = DefineComponent<IconProps>;



// Icon names type
export type IconName = 'heart' | 'home' | 'search' | 'settings' | 'user';

// Component names type
export type ComponentName = 'HeartIcon' | 'HomeIcon' | 'SearchIcon' | 'SettingsIcon' | 'UserIcon';

