export { useBattery, useDevice, useGeolocation, useNetwork } from './composables/useDevice.js';
export { cleanupGlobalDetector, vDevice, vDeviceDesktop, vDeviceMobile, vDeviceTablet } from './directives/vDevice.js';
export { default as DevicePlugin, createDevicePlugin, default, useDeviceDetector } from './plugin/index.js';
export { DeviceDetector } from '../core/DeviceDetector.js';
export { EventEmitter } from '../core/EventEmitter.js';
export { ModuleLoader } from '../core/ModuleLoader.js';
export { NetworkModule } from '../modules/NetworkModule.js';
export { BatteryModule } from '../modules/BatteryModule.js';
export { GeolocationModule } from '../modules/GeolocationModule.js';
export { BatteryInfo, DeviceDetectorEvents, DeviceDetectorOptions, DeviceDirectiveValue, DeviceInfo, DeviceModule, DevicePluginOptions, DeviceType, EventListener, GeolocationInfo, ModuleLoader as IModuleLoader, NetworkInfo, NetworkStatus, NetworkType, Orientation, UseDeviceReturn } from '../types/index.js';
