import { series } from 'gulp';

import { transform } from '@svgr/core';
import fs from 'fs-extra';
import upperCamelCase from 'uppercamelcase';
import path from 'path';
import { clearDir } from '../../../gulp/clean-dir';

const svgDir = path.join(__dirname, '../../../svg');
const srcDir = path.join(__dirname, '../src');
const componentsDir = path.join(__dirname, '../src/components');

const parseName = (name: string) => ({
  name,
  componentName: upperCamelCase(name),
});

const getIcons = () => {
  const isFile = (fileName: string) => fs.lstatSync(fileName).isFile();

  const list = fs.readdirSync(svgDir).map((fileName: string) => path.join(svgDir, fileName))
    .filter(isFile);

  const nameList = list.map((filePath: string) => {
    const fileName = path.basename(filePath, '.svg');
    return fileName;
  }).filter((name) => !!name);
  return nameList;
};

const generateIconsIndex = () => {
  fs.ensureDirSync(srcDir);

  const initialTypeDefinitions = `import { ComponentType, SVGAttributes } from 'react';

interface Props extends SVGAttributes<SVGElement> {
  className?: string;
  fill?: string;
  stroke?: string;
  strokeWith?: number;
  width?: string | number;
  height?: string | number;
}

type Icon = ComponentType<Props>;
`;

  fs.writeFileSync(path.join(srcDir, 'index.js'), '', 'utf-8');
  fs.writeFileSync(
    path.join(srcDir, 'index.d.ts'),
    initialTypeDefinitions,
    'utf-8',
  );
};

const generateIconCode = async ({ name }: {name: string}) => {
  fs.ensureDirSync(componentsDir);

  const names = parseName(name);

  const location = path.join(svgDir, `${names.name}.svg`);
  const destination = path.join(componentsDir, `${names.name}.js`);
  const svgCode = fs.readFileSync(location, 'utf-8');
  const ComponentName = `${names.componentName}Icon`;

  // 生成时间和版本信息
  const generationTime = new Date().toISOString();
  const buildVersion = require('../../../package.json').version;

  const styleSvgCode = await transform(svgCode, {
    plugins: ['@svgr/plugin-svgo'],
    svgo: true,
    svgoConfig: {
      plugins: [
        {
          name: 'addAttributesToSVGElement',
          params: {
            attributes: [
              {
                color: 'rgba(0, 0, 0, 0.9)',
              },
            ],
          },
        },
        {
          name: 'removeAttrs',
          params: {
            attrs: [
              'fill-opacity',
            ],
          },
        },
      ],
    },
  });

  const rnCode = await transform(
    styleSvgCode,
    {
      plugins: [
        '@svgr/plugin-jsx',
        '@svgr/plugin-prettier',
      ],
      replaceAttrValues: {
        black: 'currentColor',
      },
      native: true,
      exportType: 'named',
      namedExport: ComponentName,
      prettier: true,
      prettierConfig: {
        singleQuote: true,
        openingBraceNewLine: true,
      },
    },
    { componentName: ComponentName },
  );
  // 添加详细的生成注释
  const headerComment = `/**
 * LDesign Icons - React Native Component
 *
 * This file is generated automatically by LDesign Icons build system.
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten.
 *
 * Icon: ${names.name}
 * Source: ${names.name}.svg
 * Generated: ${generationTime}
 * Build version: ${buildVersion}
 * Framework: React Native
 * Package: @ldesign/icons-react-native
 *
 * Usage:
 * import { ${ComponentName} } from '@ldesign/icons-react-native';
 * <${ComponentName} width={24} height={24} color="currentColor" />
 */

`;

  // eslint-disable-next-line no-useless-concat
  const rnComponentCode = headerComment + `${rnCode}\n` + `export default ${ComponentName};
`;

  fs.writeFileSync(destination, rnComponentCode, 'utf-8');

  return { ComponentName, name: names.name };
};

const appendToIconsIndex = ({ ComponentName, name }: { ComponentName:string, name:string }) => {
  const exportStringRn = `export { ${ComponentName} } from './components/${name}';\r\n`;
  fs.appendFileSync(
    path.join(srcDir, 'index.js'),
    exportStringRn,
    'utf-8',
  );
  const exportTypeString = `export const ${ComponentName}: Icon;\n`;
  fs.appendFileSync(
    path.join(srcDir, 'index.d.ts'),
    exportTypeString,
    'utf-8',
  );
};

export function reactNativeTask() {
  return series(
    clearDir(['packages/react-native/src']),
    async (cb) => {
      generateIconsIndex();

      const icons = getIcons();
      const promises = icons.map(async (name: string) => {
        const result = await generateIconCode({ name });
        appendToIconsIndex(result);
        return result;
      });

      await Promise.all(promises);
      cb();
    },
  );
}
