/**
 * 核心功能导出模块
 * 包含主题管理、存储、系统检测等核心功能
 */

// 存储实现
export {
  CookieStorage,
  createLRUCache,
  createStorage,
  defaultCache,
  defaultStorage,
  LocalStorage,
  LRUCacheImpl,
  MemoryStorage,
  NoStorage,
  SessionStorage,
} from '../core/storage'

// 系统主题检测器
export {
  browserDetector,
  BrowserSystemThemeDetector,
  createSystemThemeDetector,
  createThemeMediaQuery,
  getSystemTheme,
  isSystemThemeSupported,
  ManualSystemThemeDetector,
  watchSystemTheme,
} from '../core/system-theme-detector'

// 主题管理器
export { ThemeManager } from '../core/theme-manager'

// 核心类型定义
export type {
  BaseColorConfig,
  BaseThemeConfig,
  CacheItem,
  CacheOptions,
  ColorAnalysisResult,
  ColorCategory,
  ColorConfig,
  ColorConversionOptions,
  ColorFormat,
  ColorGenerator,
  ColorMode,
  ColorScale,
  ColorSpace,
  ColorValidationResult,
  ColorValue,
  CSSInjector,
  ErrorEventData,
  EventEmitter,
  GeneratedTheme,
  HexColor,
  HslColor,
  HsvColor,
  IdleProcessor,
  LRUCache,
  ModeChangeEventData,
  NamedColor,
  NeutralColorCategory,
  NeutralColors,
  RgbColor,
  Storage,
  StrictColorConfig,
  StrictThemeConfig,
  SystemThemeDetector,
  TextSize,
  ThemeChangeEventData,
  ThemeConfig,
  ThemeEventDataMap,
  ThemeEventListener,
  ThemeEventType,
  ThemeManagerInstance,
  ThemeManagerOptions,
  ThemeMetadata,
  ThemeType,
  WCAGLevel,
} from '../core/types'

// 预设主题
export {
  createCustomTheme,
  cyanTheme,
  darkTheme,
  defaultTheme,
  getPresetTheme,
  getPresetThemeNames,
  getRandomPresetTheme,
  getThemesByCategory,
  getThemesByTag,
  greenTheme,
  isPresetTheme,
  minimalTheme,
  orangeTheme,
  pinkTheme,
  presetThemes,
  purpleTheme,
  recommendThemes,
  redTheme,
  themeCategories,
  themeTags,
  yellowTheme,
} from '../themes/presets'

// 高级类型定义
export type {
  AdvancedColorType,
  CacheStrategyConfig,
  ColorAnalysisConfig,
  ColorBlendConfig,
  ColorConversionConfig,
  ColorGenerationStrategy,
  ColorHarmonyType,
  ColorOperationResult,
  ColorValidationRules,
  InterpolationAlgorithm,
  LABColor,
  LCHColor,
  PaletteGenerationConfig,
  PerformanceConfig,
  PreciseHSL,
  PreciseHSV,
  PreciseRGB,
  ThemeGenerationOptions,
} from '../types/advanced'

// 工具类型定义
export type {
  AsyncEventHandler,
  AsyncFactory,
  AsyncMapper,
  Brand,
  BrandFactory,
  ColorMatrix,
  ColorRange,
  ColorTuple,
  Config,
  Constructor,
  DeepPartial,
  DeepReadonly,
  DeepRequired,
  EventHandler,
  Factory,
  HexColorBrand,
  HslColorBrand,
  JSONValue,
  Mapper,
  Option,
  Predicate,
  Range,
  Result,
  RgbColorBrand,
  Serializable,
  TypeGuard,
  UnBrand,
  ValueOf,
} from '../types/utility'
