/**
 * LDesign Icons - React Component
 *
 * This file is generated automatically by LDesign Icons build system.
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten.
 *
 * Icon: $KEY
 * Source: $KEY.svg
 * Generated: $GENERATION_TIME
 * Build version: $BUILD_VERSION
 * Framework: React
 * Package: @ldesign/icons-react
 *
 * Usage:
 * import { $ICON_NAME } from '@ldesign/icons-react';
 * <$ICON_NAME size={24} color="currentColor" />
 */

import { createElement,forwardRef, Ref } from 'react';
import { IconBase, IconProps } from '../icon';

const element = $ELEMENT;

const $ICON_NAME = forwardRef<SVGElement, IconProps>((props: IconProps, ref: Ref<SVGElement>) => createElement(
  IconBase,
  {
    ...props,
    id: '$KEY',
    ref,
    icon: element,
  },
));

$ICON_NAME.displayName = '$ICON_NAME';

export default $ICON_NAME;
